/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper */

#ifndef _Included_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
#define _Included_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
 * Method:    runScript
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper_runScript
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
